### ISSUE TITLE
How to hide right panel?

### ISSUE THREAD

**Issue by livc** [dinhviethoa/dejalu#17]
How to hide right panel like the image in README?
![](https://raw.githubusercontent.com/dinhviethoa/dejalu/master/screenshot.jpg)

This is my window.
![screen shot](https://user-images.githubusercontent.com/11692045/34809653-4ec517c8-f6d1-11e7-83a4-b83f0dfc9519.png)

**Comment by dinhviethoa** [comment]
Window > Hide Details.

**Comment by livc** [comment]
Thanks for the reply.
