### ISSUE TITLE
Reply to specific message in thread

### ISSUE THREAD

**Issue by disq** [dinhviethoa/dejalu#2]
Replying to a specific message in a thread doesn't seem to be supported. Something like, there's a mail thread, somebody replied before you and added some recipients as well, and you'd like to reply to (and quote) one of the older messages in the thread.

**Comment by dinhviethoa** [comment]
You can click on a specific message to Reply.
The visual cue is that the date becomes blue when it's "selected"

**Comment by disq** [comment]
Wow, thanks!
