### ISSUE TITLE
Cut new release?

### ISSUE THREAD

**Issue by danielcompton** [dinhviethoa/dejalu#30]
It looks like Sparkle updating has been added, would you consider cutting a new release so that people will get future updates? Or is there another update mechanism in the old versions?

**Comment by dinhviethoa** [comment]
I can trigger a release manually. Let me do that this week.

**Comment by tuananh** [comment]
I got this error when update

![image](https://user-images.githubusercontent.com/627278/35439183-396cbabe-02cc-11e8-8fe8-c515c9c9e7f0.png)

**Comment by sanzot** [comment]
Same happen to me :-(

**Comment by omartin** [comment]
Here too.

**Comment by dinhviethoa** [comment]
It's been fixed. Sorry for the trouble!

**Comment by sanzot** [comment]
Solved. Thks
