### ISSUE TITLE
Answering a thread of emails

### ISSUE THREAD

**Issue by sanzot** [dinhviethoa/dejalu#36]
Use case: You send an email to many people. Then they individually response you. If you want to answer to this second to each person it's only possible to the last one. In a general basis in a thread of email it's not possible to answer to each one but just the last one. 

Thanks. 
Santi

**Comment by tuananh** [comment]
so you want reply all always?

**Comment by dinhviethoa** [comment]
You can click on a specific message (you'll notice that the date turns blue) and then hitting reply will reply to this specific email.

**Comment by sanzot** [comment]
Right. it is not obvious. Many thanks.
