### ISSUE TITLE
MacOS Mojave, sidebar background color issue

### ISSUE THREAD

**Issue by disq** [dinhviethoa/dejalu#44]
See attached screenshot. If I disable the sidebar, list of emails panel (whatever's the leftmost pane) gets this issue.

If the app doesn't have the focus, the color scheme works as expected (just as in High Sierra etc.)

<img width="174" alt="screen shot 2018-10-01 at 13 18 58" src="https://user-images.githubusercontent.com/223029/46283324-bf3f1880-c57c-11e8-8335-031d7dd3e20b.png">

**Comment by disq** [comment]
Update: it seems to be transparent -- I missed it. Here's another pic:

![screen shot 2018-10-01 at 22 27 03](https://user-images.githubusercontent.com/223029/46310865-3bf7e400-c5c9-11e8-8237-53b307cba5f7.png)

**Comment by dinhviethoa** [comment]
Maybe I start disabling translucency. I think Apple did that on their apps too.

**Comment by dinhviethoa** [comment]
I think that's fixed now.
