### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by lucashoeft** [dinhviethoa/dejalu#5]
I'd like to have a detailed installation guide, because the pictures are looking good, but I'm not really into iOS/macOS development so I have no idea how to install the email client on my computer.

**Comment by oskarkrawczyk** [comment]
There's a download link on the website https://t.co/XPkm0Utbj7

--

**Comment by lucashoeft** [comment]
Oh, thanks. Didn't know a website exist. I didn't found the download link on the website you posted, but a quick google search helped me. Would be great if @dinhviethoa could add the link to the website in README or to the repository header.

**Comment by dinhviethoa** [comment]
I added the link. Thanks!
