### ISSUE TITLE
"Clean up" button covers search icon

### ISSUE THREAD

**Issue by aleksandergrzyb** [dinhviethoa/dejalu#51]
"Clean up" button covers search icon when selecting specific inbox:

<img width="113" alt="screenshot 2019-01-02 at 19 04 23" src="https://user-images.githubusercontent.com/3186691/50605039-5475e400-0ec1-11e9-8aa8-cd4d0cf14779.png">

**Comment by dinhviethoa** [comment]
I think that's fixed with the latest build.
